// Popular airports - sorted alphabetically by city
export const airports = [
  // Europe
  { code: 'AMS', city: 'Amsterdam', name: 'Schiphol', country: 'Netherlands' },
  { code: 'ATH', city: 'Athens', name: 'Eleftherios Venizelos', country: 'Greece' },
  { code: 'BCN', city: 'Barcelona', name: 'El Prat', country: 'Spain' },
  { code: 'TXL', city: 'Berlin', name: 'Brandenburg', country: 'Germany' },
  { code: 'BRU', city: 'Brussels', name: 'Brussels Airport', country: 'Belgium' },
  { code: 'OTP', city: 'Bucharest', name: 'Henri Coandă', country: 'Romania' },
  { code: 'BUD', city: 'Budapest', name: 'Ferenc Liszt', country: 'Hungary' },
  { code: 'CPH', city: 'Copenhagen', name: 'Kastrup', country: 'Denmark' },
  { code: 'DUB', city: 'Dublin', name: 'Dublin Airport', country: 'Ireland' },
  { code: 'EDI', city: 'Edinburgh', name: 'Edinburgh Airport', country: 'UK' },
  { code: 'FRA', city: 'Frankfurt', name: 'Frankfurt Airport', country: 'Germany' },
  { code: 'GVA', city: 'Geneva', name: 'Geneva Airport', country: 'Switzerland' },
  { code: 'HEL', city: 'Helsinki', name: 'Vantaa', country: 'Finland' },
  { code: 'IST', city: 'Istanbul', name: 'Istanbul Airport', country: 'Turkey' },
  { code: 'LIS', city: 'Lisbon', name: 'Humberto Delgado', country: 'Portugal' },
  { code: 'LHR', city: 'London', name: 'Heathrow', country: 'UK' },
  { code: 'LGW', city: 'London', name: 'Gatwick', country: 'UK' },
  { code: 'STN', city: 'London', name: 'Stansted', country: 'UK' },
  { code: 'MAD', city: 'Madrid', name: 'Barajas', country: 'Spain' },
  { code: 'MAN', city: 'Manchester', name: 'Manchester Airport', country: 'UK' },
  { code: 'MXP', city: 'Milan', name: 'Malpensa', country: 'Italy' },
  { code: 'SVO', city: 'Moscow', name: 'Sheremetyevo', country: 'Russia' },
  { code: 'MUC', city: 'Munich', name: 'Franz Josef Strauss', country: 'Germany' },
  { code: 'NCE', city: 'Nice', name: 'Côte d\'Azur', country: 'France' },
  { code: 'OSL', city: 'Oslo', name: 'Gardermoen', country: 'Norway' },
  { code: 'CDG', city: 'Paris', name: 'Charles de Gaulle', country: 'France' },
  { code: 'ORY', city: 'Paris', name: 'Orly', country: 'France' },
  { code: 'PRG', city: 'Prague', name: 'Václav Havel', country: 'Czech Republic' },
  { code: 'FCO', city: 'Rome', name: 'Fiumicino', country: 'Italy' },
  { code: 'ARN', city: 'Stockholm', name: 'Arlanda', country: 'Sweden' },
  { code: 'VIE', city: 'Vienna', name: 'Vienna International', country: 'Austria' },
  { code: 'WAW', city: 'Warsaw', name: 'Chopin', country: 'Poland' },
  { code: 'ZRH', city: 'Zurich', name: 'Zurich Airport', country: 'Switzerland' },
  
  // North America
  { code: 'ATL', city: 'Atlanta', name: 'Hartsfield-Jackson', country: 'USA' },
  { code: 'BOS', city: 'Boston', name: 'Logan International', country: 'USA' },
  { code: 'ORD', city: 'Chicago', name: 'O\'Hare', country: 'USA' },
  { code: 'DFW', city: 'Dallas', name: 'Dallas/Fort Worth', country: 'USA' },
  { code: 'DEN', city: 'Denver', name: 'Denver International', country: 'USA' },
  { code: 'DTW', city: 'Detroit', name: 'Detroit Metro', country: 'USA' },
  { code: 'HNL', city: 'Honolulu', name: 'Daniel K. Inouye', country: 'USA' },
  { code: 'IAH', city: 'Houston', name: 'George Bush', country: 'USA' },
  { code: 'LAS', city: 'Las Vegas', name: 'Harry Reid', country: 'USA' },
  { code: 'LAX', city: 'Los Angeles', name: 'Los Angeles International', country: 'USA' },
  { code: 'MIA', city: 'Miami', name: 'Miami International', country: 'USA' },
  { code: 'MSP', city: 'Minneapolis', name: 'Minneapolis-Saint Paul', country: 'USA' },
  { code: 'YUL', city: 'Montreal', name: 'Trudeau', country: 'Canada' },
  { code: 'JFK', city: 'New York', name: 'John F. Kennedy', country: 'USA' },
  { code: 'EWR', city: 'Newark', name: 'Newark Liberty', country: 'USA' },
  { code: 'MCO', city: 'Orlando', name: 'Orlando International', country: 'USA' },
  { code: 'PHL', city: 'Philadelphia', name: 'Philadelphia International', country: 'USA' },
  { code: 'PHX', city: 'Phoenix', name: 'Sky Harbor', country: 'USA' },
  { code: 'SAN', city: 'San Diego', name: 'San Diego International', country: 'USA' },
  { code: 'SFO', city: 'San Francisco', name: 'San Francisco International', country: 'USA' },
  { code: 'SEA', city: 'Seattle', name: 'Seattle-Tacoma', country: 'USA' },
  { code: 'YYZ', city: 'Toronto', name: 'Pearson', country: 'Canada' },
  { code: 'YVR', city: 'Vancouver', name: 'Vancouver International', country: 'Canada' },
  { code: 'IAD', city: 'Washington', name: 'Dulles', country: 'USA' },
  { code: 'DCA', city: 'Washington', name: 'Reagan National', country: 'USA' },
  
  // Asia
  { code: 'BKK', city: 'Bangkok', name: 'Suvarnabhumi', country: 'Thailand' },
  { code: 'PEK', city: 'Beijing', name: 'Capital International', country: 'China' },
  { code: 'DEL', city: 'Delhi', name: 'Indira Gandhi', country: 'India' },
  { code: 'DXB', city: 'Dubai', name: 'Dubai International', country: 'UAE' },
  { code: 'HKG', city: 'Hong Kong', name: 'Hong Kong International', country: 'Hong Kong' },
  { code: 'CGK', city: 'Jakarta', name: 'Soekarno-Hatta', country: 'Indonesia' },
  { code: 'KUL', city: 'Kuala Lumpur', name: 'Kuala Lumpur International', country: 'Malaysia' },
  { code: 'MNL', city: 'Manila', name: 'Ninoy Aquino', country: 'Philippines' },
  { code: 'BOM', city: 'Mumbai', name: 'Chhatrapati Shivaji', country: 'India' },
  { code: 'KIX', city: 'Osaka', name: 'Kansai', country: 'Japan' },
  { code: 'ICN', city: 'Seoul', name: 'Incheon', country: 'South Korea' },
  { code: 'PVG', city: 'Shanghai', name: 'Pudong', country: 'China' },
  { code: 'SIN', city: 'Singapore', name: 'Changi', country: 'Singapore' },
  { code: 'TPE', city: 'Taipei', name: 'Taoyuan', country: 'Taiwan' },
  { code: 'NRT', city: 'Tokyo', name: 'Narita', country: 'Japan' },
  { code: 'HND', city: 'Tokyo', name: 'Haneda', country: 'Japan' },
  
  // Middle East & Africa
  { code: 'AMM', city: 'Amman', name: 'Queen Alia', country: 'Jordan' },
  { code: 'CAI', city: 'Cairo', name: 'Cairo International', country: 'Egypt' },
  { code: 'CMN', city: 'Casablanca', name: 'Mohammed V', country: 'Morocco' },
  { code: 'DOH', city: 'Doha', name: 'Hamad International', country: 'Qatar' },
  { code: 'JNB', city: 'Johannesburg', name: 'O.R. Tambo', country: 'South Africa' },
  { code: 'NBO', city: 'Nairobi', name: 'Jomo Kenyatta', country: 'Kenya' },
  { code: 'RUH', city: 'Riyadh', name: 'King Khalid', country: 'Saudi Arabia' },
  { code: 'TLV', city: 'Tel Aviv', name: 'Ben Gurion', country: 'Israel' },
  
  // Oceania
  { code: 'AKL', city: 'Auckland', name: 'Auckland Airport', country: 'New Zealand' },
  { code: 'BNE', city: 'Brisbane', name: 'Brisbane Airport', country: 'Australia' },
  { code: 'MEL', city: 'Melbourne', name: 'Tullamarine', country: 'Australia' },
  { code: 'PER', city: 'Perth', name: 'Perth Airport', country: 'Australia' },
  { code: 'SYD', city: 'Sydney', name: 'Kingsford Smith', country: 'Australia' },
  
  // South America
  { code: 'EZE', city: 'Buenos Aires', name: 'Ezeiza', country: 'Argentina' },
  { code: 'LIM', city: 'Lima', name: 'Jorge Chávez', country: 'Peru' },
  { code: 'MEX', city: 'Mexico City', name: 'Benito Juárez', country: 'Mexico' },
  { code: 'GRU', city: 'São Paulo', name: 'Guarulhos', country: 'Brazil' },
  { code: 'SCL', city: 'Santiago', name: 'Arturo Merino Benítez', country: 'Chile' },
];

// Helper to find airport by code
export const getAirportByCode = (code) => airports.find((a) => a.code === code);

